Repository mhmdsami/pet-store-api, pull requests merged in 2022-10, with the labels that each got.

#3 Handle 401
  src/api/pets.ts
Labels: hacktoberfest-accepted

#4 Add Request Body Validation
  src/api/pets.ts
Labels: hacktoberfest, hacktoberfest-accepted

#7 added a parameter of category
  src/api/controllers/pets.controller.ts
Labels: hacktoberfest
